export const BOUNTY_ABI = [{ "type": "constructor", "inputs": [], "stateMutability": "nonpayable" }, {
    "type": "function", "name": "bounties", "inputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }], "outputs": [{ "name": "creator", "type": "address", "internalType": "address" }, { "name": "deadline", "type": "uint256", "internalType": "uint256" },
    { "name": "bountyAmount", "type": "uint256", "internalType": "uint256" },
    { "name": "bountyId", "type": "uint256", "internalType": "uint256" }, { "name": "imageUrl", "type": "string", "internalType": "string" }, { "name": "description", "type": "string", "internalType": "string" }, { "name": "expectation", "type": "string", "internalType": "string" }, { "name": "title", "type": "string", "internalType": "string" },
    { "name": "category", "type": "uint8", "internalType": "enum BountyV1.Category" }, { "name": "status", "type": "uint8", "internalType": "enum BountyV1.BountyStatus" }, { "name": "participation", "type": "uint256", "internalType": "uint256" }], "stateMutability": "view"
}, {
    "type": "function", "name": "closeBounty", "inputs": [{ "name": "_bountyId", "type": "uint256", "internalType": "uint256" }],
    "outputs": [], "stateMutability": "nonpayable"
}, {
    "type": "function", "name": "createBounty", "inputs": [{ "name": "_title", "type": "string", "internalType": "string" }, { "name": "_description", "type": "string", "internalType": "string" }, { "name": "_expectation", "type": "string", "internalType": "string" }, { "name": "imageUrl", "type": "string", "internalType": "string" }, { "name": "_category", "type": "uint8", "internalType": "enum BountyV1.Category" },
    { "name": "_deadline", "type": "uint256", "internalType": "uint256" },
    { "name": "_bountyAmount", "type": "uint256", "internalType": "uint256" }], "outputs": [], "stateMutability": "payable"
}, { "type": "function", "name": "deleteBounty", "inputs": [{ "name": "_bountyId", "type": "uint256", "internalType": "uint256" }], "outputs": [], "stateMutability": "nonpayable" },
{
    "type": "function", "name": "loadBountieByCategory", "inputs": [{ "name": "_category", "type": "uint8", "internalType": "uint8" }], "outputs": [{
        "name": "", "type": "tuple[]", "internalType": "struct BountyV1.Bounty[]", "components": [{ "name": "creator", "type": "address", "internalType": "address" }, { "name": "deadline", "type": "uint256", "internalType": "uint256" }, { "name": "bountyAmount", "type": "uint256", "internalType": "uint256" },
        { "name": "bountyId", "type": "uint256", "internalType": "uint256" }, { "name": "imageUrl", "type": "string", "internalType": "string" }, { "name": "description", "type": "string", "internalType": "string" }, { "name": "expectation", "type": "string", "internalType": "string" }, { "name": "title", "type": "string", "internalType": "string" }, { "name": "category", "type": "uint8", "internalType": "enum BountyV1.Category" },
        { "name": "status", "type": "uint8", "internalType": "enum BountyV1.BountyStatus" }, { "name": "participation", "type": "uint256", "internalType": "uint256" }]
    }], "stateMutability": "view"
}, {
    "type": "function", "name": "loadBounties", "inputs": [{ "name": "_bountyIds", "type": "uint256[]", "internalType": "uint256[]" }], "outputs": [{
        "name": "", "type": "tuple[]", "internalType": "struct BountyV1.Bounty[]", "components": [{ "name": "creator", "type": "address", "internalType": "address" }, { "name": "deadline", "type": "uint256", "internalType": "uint256" }, { "name": "bountyAmount", "type": "uint256", "internalType": "uint256" }, { "name": "bountyId", "type": "uint256", "internalType": "uint256" }, { "name": "imageUrl", "type": "string", "internalType": "string" }, { "name": "description", "type": "string", "internalType": "string" },
        { "name": "expectation", "type": "string", "internalType": "string" }, { "name": "title", "type": "string", "internalType": "string" }, { "name": "category", "type": "uint8", "internalType": "enum BountyV1.Category" }, { "name": "status", "type": "uint8", "internalType": "enum BountyV1.BountyStatus" }, { "name": "participation", "type": "uint256", "internalType": "uint256" }]
    }], "stateMutability": "view"
}, { "type": "function", "name": "nextBountyId", "inputs": [], "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }], "stateMutability": "view" }, { "type": "function", "name": "owner", "inputs": [], "outputs": [{ "name": "", "type": "address", "internalType": "address" }], "stateMutability": "view" }, { "type": "function", "name": "returnBountyId", "inputs": [], "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }], "stateMutability": "view" }, { "type": "function", "name": "submitApplication", "inputs": [{ "name": "applicant", "type": "address", "internalType": "address" }, { "name": "bountyId", "type": "uint256", "internalType": "uint256" }, { "name": "coverLetter", "type": "string", "internalType": "string" }, { "name": "proposal", "type": "string", "internalType": "string" }, { "name": "workUrl", "type": "string", "internalType": "string" }], "outputs": [], "stateMutability": "nonpayable" }, {
    "type": "event", "name": "BountyCreated", "inputs": [{ "name": "bountyId", "type": "uint256", "indexed": true, "internalType": "uint256" }, { "name": "creator", "type": "address", "indexed": true, "internalType": "address" }, { "name": "title", "type": "string", "indexed": false, "internalType": "string" }, { "name": "bountyAmount", "type": "uint256", "indexed": false, "internalType": "uint256" },
    { "name": "deadline", "type": "uint256", "indexed": false, "internalType": "uint256" }], "anonymous": false
}]